http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.89.2.12
    - 10.89.2.1
    - 10.89.2.2
    - ::1
    - 10.89.2.0/24

switch:
  - platform: wake_on_lan
    mac: 72:45:5a:de:74:b5
    name: workstation-oni-wlp12s0

wake_on_lan:
