- id: '1747725946121'
  name: New scene
  entities:
    light.wiz_rgbw_tunable_849b7c:
      min_color_temp_kelvin: 2200
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 454
      effect_list:
      - Ocean
      - Romance
      - Sunset
      - Party
      - Fireplace
      - Cozy
      - Forest
      - Pastel Colors
      - Wake up
      - Bedtime
      - Warm White
      - Daylight
      - Cool white
      - Night light
      - Focus
      - Relax
      - True colors
      - TV time
      - Plantgrowth
      - Spring
      - Summer
      - Fall
      - Deepdive
      - Jungle
      - Mojito
      - Club
      - Christmas
      - Halloween
      - Candlelight
      - Golden white
      - Pulse
      - Steampunk
      - Rhythm
      supported_color_modes:
      - color_temp
      - rgbw
      effect: Daylight
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 4200
      color_temp: 238
      hs_color:
      - 26.743
      - 31.364
      rgb_color:
      - 255
      - 211
      - 175
      xy_color:
      - 0.408
      - 0.362
      rgbw_color:
      friendly_name: WiZ RGBW Tunable 849B7C
      supported_features: 4
      state: 'on'
  icon: mdi:sun-clock
  metadata: {}
- id: '1747726582537'
  name: Wake up
  entities:
    light.wiz_rgbw_tunable_849b7c:
      min_color_temp_kelvin: 2200
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 454
      effect_list:
      - Ocean
      - Romance
      - Sunset
      - Party
      - Fireplace
      - Cozy
      - Forest
      - Pastel Colors
      - Wake up
      - Bedtime
      - Warm White
      - Daylight
      - Cool white
      - Night light
      - Focus
      - Relax
      - True colors
      - TV time
      - Plantgrowth
      - Spring
      - Summer
      - Fall
      - Deepdive
      - Jungle
      - Mojito
      - Club
      - Christmas
      - Halloween
      - Candlelight
      - Golden white
      - Pulse
      - Steampunk
      - Rhythm
      supported_color_modes:
      - color_temp
      - rgbw
      effect: Wake up
      color_mode: unknown
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      rgbw_color:
      friendly_name: WiZ RGBW Tunable 849B7C
      supported_features: 4
      state: 'on'
  metadata: {}
  icon: mdi:sun-clock
